spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.167.102/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=VHGj6x26w0IpAlMhgDUWRnUj
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:ZuEIAgCw4rB9aPDsjqCEX4r5@172.21.126.137:27017/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 
